path:
    driver: "./exe/chromedriver.exe"
    data: "./data"

driver_options:
    - "--disable-popup-blocking"
    - "--disable-extensions"
    - "--disable-gpu"
    - "--no-sandbox"
    - "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"

dotnet:
    common:
        bulletin: "https://support.microsoft.com/{}/help/{}"
        nations:
            - ja-jp
            - ko-kr
            - zh-cn
            - en-us

    re:
        cve: "CVE-\\d+-\\d+"
        cve_id: "^cve"
        kb: "^KB\\d{7}"

    xpath:
        title: "//*[@id=\"ScopedViewHandler_titleText\"]"
        severity: "//*[@id=\"ScopedViewHandler_msrcSeverity\"]"
        download: "//*[@id=\"downloadFiles\"]"

    id:
        header: "page-header"
        summary: "bkmk_summary"